name: Flask CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  VERSION: v1.0.${{ github.run_number }}

jobs:

  build-test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python -m pytest -v

    - name: Build Docker Image
      run: |
        docker build \
           -t flask-api:${{ env.VERSION }} .

  deploy:
        needs: build-test

        runs-on: ubuntu-latest

        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4

          - name: Create Kind Cluster
            uses: helm/kind-action@v1

          - name: Setup Helm
            uses: azure/setup-helm@v4

          - name: Verify Cluster
            run: |
                kubectl cluster-info
                kubectl get nodes

          - name: Deploy
            run: |
                helm upgrade --install flask-api ./helm/flask-api \
                --set image.repository=flask-api \
                --set image.tag=${{ github.sha }}

          - name: Verify Deployment
            run: |
                kubectl get pods
                kubectl get svc